services:
  - type: worker
    name: crossfit-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: crossfit-db
          property: connectionString

  - type: worker
    name: crossfit-parser
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python parser.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crossfit-db
          property: connectionString
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: CHANNELS
        sync: false

databases:
  - name: crossfit-db
    plan: free
